app:
  firebase:
    file: binar-ra-cinema-firebase.json
  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890

server:
  port: 8081

spring:
  application:
    name: NOTIFICATION-SERVICE

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka